FROM registry.mahnke.tech/mktech/build:2025-02.00

# RUN pacman --noconfirm -Syu \
#    package \

# RUN pacman --noconfirm -Scc

ARG source_name=mktech-mktech
ARG source_dir=/usr/local/src/$source_name

RUN mkdir -p $source_dir && chmod 777 $source_dir

WORKDIR $source_dir

COPY . .
